### ISSUE TITLE
Automatic URL redirecting?

### ISSUE THREAD

**Issue by SlidingHorn** [tats/w3m#186]
Shot in the dark here: Is it possible to have w3m read a particular string in a URL and modify it accordingly?

**Example:** 

- check for `reddit.com` in the URL
- if it exists, add `.mobile` to the end of the URL

---

I've searched all over, but couldn't find anything, so I'm assuming it's not possible. I just figured I'd give one last shot and ask here.

**Comment by Boruch-Baum** [comment]
On 2021-07-08 12:30, SlidingHorn wrote:
>    Shot in the dark here: Is it possible to have w3m read a particular
>    string in a URL and modify it accordingly?
>
>    Example:
>      * check for reddit.com in the URL
>      * if it exists, add .mobile to the end of the URL
>
>    I've searched all over, but couldn't find anything, so I'm assuming
>    it's not possible. I just figured I'd give one last shot and ask here.

Oooo. Nice request! I don't know of any w3m-native method for doing what
you want, but if you use the emacs front-end for w3m (ie. emacs-w3m), it
seems to me that you should be able to do this with a simple addition to
variable w3m-uri-replace-alist.

Here's an excerpt from the first part of that variable's doc-string:

   Alist of regexps matching URIs, and some types of replacements. It
   can be used universally to replace URI strings in the local rule to
   the valid forms in the Internet.

   REGEXP may include grouping constructs "\(...\)", so that they can be
   referred by the "N" forms in a replacement (which is one of OPTIONS).

Your request might be do-able by adding to that data structure an entry
something like:

  ("\\(.*reddit.com.*\\)" w3m-pattern-uri-replace "\\1.mobile")

or maybe just:

  (".*reddit.com.*" w3m-pattern-uri-replace "\\0.mobile")

I haven't tried this myself so if anyone on list does try, please let me
know if it succeeds or fails.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by gotbletu** [comment]
`$EDITOR ~/.w3m/siteconf`

```
url m@^https?://(.*\.)reddit\.com.*/$@
substitute_url ".mobile"
```

e.g open address bar, type in,  `reddit.com/r/linux/`
note: you might need a trailing slash at the end for it to do a redirect to `.mobile`

**Comment by SlidingHorn** [comment]
> `$EDITOR ~/.w3m/siteconf`
> 
> ```
> url m@^https?://(.*\.)reddit\.com.*/$@
> substitute_url ".mobile"
> ```
> 
> e.g open address bar, type in, `reddit.com/r/linux/`
> note: you might need a trailing slash at the end for it to do a redirect to `.mobile`

That's **exactly** what I needed. Thank you.

P.S. I *just* watched your video about gopher on w3m the other day. :+1:
