### ISSUE TITLE
Can't toggle mark_all_pages from within w3m?

### ISSUE THREAD

**Issue by 097115** [tats/w3m#194]
Steps to reproduce:

1. `echo http://google.com | w3m`
2. `COMMAND` (mapped to M-c by default) -> `SET_OPTION mark_all_pages=1 ; RESHAPE`
3. Nothing happens (can't open/navigate to google.com)

However, if I add this option to the command line, like `echo http://google.com | w3m -o mark_all_pages=1`, then the link is highlighted and I can open it.

w3m version w3m/0.5.3+git20200823, installed with MacPorts.

**Comment by rkta** [comment]
First problem here is that the buffer is read from stdin. RESHAPE
expects the buffer to be connected to a file. If that's not the case
it's basically a silent no-op (RELOAD, on the other hand, gives a warning).

But the problem also exists with the following case:
% echo http://google.com > url
% w3m url
Then use 'COMMAND' to invoke 'SET_OPTION mark_all_pages=1'.

Now 'RESHAPE' also doesn't work, but because that buffer's 'check_url' is not
updated after changing the option. 'RELOAD' updates 'check_url' and
displays the link as desired. That's all I can say after a quick
debugging session.

So, as a workaround: read from a file and use RELOAD instead of RESHAPE.

**Comment by rkta** [comment]
So, after a second look:
To turn URL-like strings into hyperlinks when the buffer is read from
stdin use MARK_URL (default bound to ':').

RESHAPE is only useful if the size of the terminal has changed or the
buffer content has changed (so that the line lengths has changed). I
can't think of use-case when one wants to invoke it manually.

**Comment by 097115** [comment]
@rkta 

Thanks! Closing this?

**Comment by rkta** [comment]
On Sun, Sep 19, 2021 at 01:18:02AM -0700, 097115 wrote:
> @rkta 
> 
> Thanks! Closing this?

Yep.
